// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPS
{
        public const string achievement_fly_round_25_birds = "CgkInu7ap-ETEAIQCw"; // <GPGSID>
        public const string achievement_first_loss = "CgkInu7ap-ETEAIQCQ"; // <GPGSID>
        public const string achievement_one_more = "CgkInu7ap-ETEAIQBA"; // <GPGSID>
        public const string achievement_fly_round_50_birds = "CgkInu7ap-ETEAIQDA"; // <GPGSID>
        public const string achievement_first_1000_coins = "CgkInu7ap-ETEAIQCA"; // <GPGSID>
        public const string achievement_first_bird = "CgkInu7ap-ETEAIQAw"; // <GPGSID>
        public const string achievement_first_10_coins = "CgkInu7ap-ETEAIQAQ"; // <GPGSID>
        public const string achievement_and_one_more = "CgkInu7ap-ETEAIQBQ"; // <GPGSID>
        public const string leaderboard_airman = "CgkInu7ap-ETEAIQBw"; // <GPGSID>
        public const string leaderboard_rich_man = "CgkInu7ap-ETEAIQBg"; // <GPGSID>
        public const string achievement_fly_round_10_birds = "CgkInu7ap-ETEAIQCg"; // <GPGSID>
        public const string achievement_first_100_coins = "CgkInu7ap-ETEAIQAg"; // <GPGSID>

}

